### ISSUE TITLE
UPDATING LIST FOR NEXT DAY

### ISSUE THREAD

**Issue by sykes140** [ammaarpatel99/pharm-manager#1]
Getting my head round the program. Just feel it would be good if the order pad maintains unticked items on the day it was initially written on pad as well as updating unmarked ones on to the next day so that we are aware that there is a supply issue and not just complacency in ordering items.

**Comment by ammaarpatel99** [comment]
double check this but I'm pretty sure it does. When the order pad moves into the next day it should make a copy of any unordered items in the history.
Also,  just so you know,  since the data is stored in the browser it is possible to test things without affecting your data. If you open a private window (on chrome it's an incognito window) or a different browser, the website will have a separate database, so changes won't cross over. So to edit you stuff you have to always use the same browser, but if you wanted to test something you can just use a different one. Private browsers (i.e. incognito) is probably better for testing because changes don't persist, i.e. anything you do or save on an incognito window is deleted when you close the window.

**Comment by ammaarpatel99** [comment]
I've checked this, and unordered items are definitely recorded in history when the day's order is completed (by moving the order pad to the next day). However when you move the order pad to the next day the ordered items remain on the order pad at the moment (they're not suppose to). If you reload or go to a different page and back then they've gone (and are only in the history of the previous day, as expected), so it's just a bug and it doesn't seem like a problem. I've recorded it at #2 .

I'm closing this issue, since I'm pretty sure it already does what you want it to. If I'm wrong just reply.
